name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake animations
        uses: Platane/snk@v3
        with:
          github_user_name: magestacks
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake.gif
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKE_ACCESS_TOKEN }}

      - name: Publish to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.SNAKE_ACCESS_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
